
export const sites = [
	{ id:1, link: '/advertisement-list', name:'Quảng Cáo' },
	{ id:2, link: '/banner-list', name:'Banner' },
	{ id:3, link: '/event/list', name:'Sự Kiện' },
	{ id:4, link: '/faq/list', name:'Câu Hỏi Thường Gặp' },
	{ id:5, link: '/feedback-list', name:'Phản Hồi' },
	{ id:6, link: '/game/list', name:'Trò Chơi' },
	{ id:7, link: '/hot/list', name:'Hot' },
	{ id:8, link: '/post/list', name:'Bài Viết' },
	{ id:9, link: '/promotion-label/list', name:'Nhãn Khuyến Mãi' },
	{ id:10, link: '/link-card-list', name:'Thẻ Liên Kết' },
	{ id:11, link: '/notification/list', name:'Thông Báo' },
	{ id:12, link: '/promotions', name:'Khuyến Mãi' },
	{ id:13, link: '/fee/list', name:'Phí Giao Dịch' },
	{ id:14, link: '/denomination-list', name:'Mệnh Giá Nạp Tiền' },
	{ id:15, link: '/hot-advs-list', name:'Hot Ads' },
	{ id:16, link: '/promotion-type-list', name:'Loại Khuyến Mãi' },
	{ id:17, link: '/open-time', name:'Giờ Mở Cửa' },
]