# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfomations',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderinfomations',
            name='order_code',
            field=models.CharField(blank=True, max_length=250, verbose_name='order_code'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='orderinfomations',
            name='money',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='money'),
        ),
        migrations.AlterField(
            model_name='orderinfomations',
            name='payment_method',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='payment_method'),
        ),
        migrations.AlterField(
            model_name='orderinfomations',
            name='status_payment',
            field=models.CharField(choices=[('payment_error', 'Payment Error'), ('pendding', 'Pendding'), ('done', 'Done')], default='Pendding', max_length=250, verbose_name='status_payment'),
        ),
        migrations.AlterField(
            model_name='products',
            name='detail',
            field=models.CharField(blank=True, max_length=250, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='products',
            name='hit_count',
            field=models.IntegerField(verbose_name='hit_count'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='shipinfomations',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='shipinfomations',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='shipinfomations',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='shipinfomations',
            name='phone',
            field=models.CharField(blank=True, max_length=250, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='phone',
            field=models.CharField(blank=True, max_length=250, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.CharField(blank=True, max_length=250, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='userbases',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userbases',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='last name'),
        ),
    ]
