# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180927_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('price', models.CharField(blank=True, max_length=250, null=True, verbose_name='price')),
                ('tax', models.IntegerField(verbose_name='tax')),
                ('quanlity', models.IntegerField(verbose_name='quanlity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='orderinfomations',
            name='address',
        ),
        migrations.AlterField(
            model_name='shipinfomations',
            name='orderInfomation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.OrderInfomations'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='orderInfomation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OrderInfomations'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Products'),
        ),
    ]
