# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 11:43
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_suppliers_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userbases',
            managers=[
                ('objects', app.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userbases',
            name='groupUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.GroupUsers'),
        ),
    ]
