# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userbases_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='hit_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='hit_count'),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('coming_soon', 'Coming soon'), ('still', 'Still'), ('oversell', 'Oversell')], default='still', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Suppliers'),
        ),
        migrations.AlterField(
            model_name='products',
            name='tax',
            field=models.IntegerField(blank=True, null=True, verbose_name='tax'),
        ),
    ]
