# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181002_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='phone',
            field=models.CharField(max_length=250, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='soft_delete',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='soft delete'),
        ),
    ]
