# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181002_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='expire_date',
            field=models.DateField(),
        ),
    ]
