# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181002_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='app.Products'),
        ),
    ]
