# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181002_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='products',
            new_name='category',
        ),
    ]
