# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20181003_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Carts'),
        ),
    ]
