# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20181003_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupusers',
            name='name',
            field=models.CharField(choices=[('customer_group', 'customer group'), ('store_group', 'store group'), ('owner_group', 'owner group')], default='1', max_length=250, unique=True, verbose_name='name'),
        ),
    ]
