# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181005_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='app.Products'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Carts'),
            preserve_default=False,
        ),
    ]
