# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20181006_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cus_user_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
