# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_carts_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('quanlity', models.IntegerField(verbose_name='quanlity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Carts')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='carts',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart_product_rel', through='app.CartDetail', to='app.Products'),
        ),
    ]
