# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20181009_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='tax',
        ),
        migrations.AddField(
            model_name='orderinfomations',
            name='products',
            field=models.ManyToManyField(related_name='order_product_rel', through='app.OrderDetails', to='app.Products'),
        ),
        migrations.AlterField(
            model_name='orderinfomations',
            name='payment_method',
            field=models.CharField(choices=[('payment_error', 'Payment Error'), ('pendding', 'Pendding'), ('done', 'Done')], default='internet_banking', max_length=250, verbose_name='payment_method'),
        ),
        migrations.AlterField(
            model_name='orderinfomations',
            name='status_order',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('payment_error', 'Payment Error'), ('create', 'Create'), ('shipping', 'Shipping'), ('done', 'Done')], default='create', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderinfomations',
            name='status_payment',
            field=models.CharField(choices=[('payment_error', 'Payment Error'), ('pendding', 'Pendding'), ('done', 'Done')], default='pendding', max_length=250, verbose_name='status_payment'),
        ),
    ]
