# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20181014_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfomations',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='transaction_id'),
        ),
        migrations.AlterField(
            model_name='orderinfomations',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customers'),
        ),
        migrations.AlterField(
            model_name='orderinfomations',
            name='payment_method',
            field=models.CharField(choices=[('ship_code', 'Ship code'), ('paypal', 'Paypal')], default='ship_code', max_length=250, verbose_name='payment_method'),
        ),
        migrations.AlterField(
            model_name='orderinfomations',
            name='status_order',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('payment_error', 'Payment Error'), ('waiting', 'Waiting'), ('accept', 'Accept'), ('shipping', 'Shipping'), ('done', 'Done')], default='create', max_length=255),
        ),
    ]
