# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20181021_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='star',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=2),
            preserve_default=False,
        ),
    ]
