# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.apps import apps



class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_feedbacks_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stores',
        ),
    ]

    print 'Remove m2m products vs store, add store onetomany product'  
    try:
        print 'Product has value show handle default value'
        store = apps.get_model(app_label='app', model_name='Stores').objects.all().first()
        operations.append(
                migrations.AddField(
                model_name='products',
                name='stores',
                field=models.ForeignKey(default=store.id, on_delete=django.db.models.deletion.CASCADE, to='app.Stores'),
                preserve_default=False,
            ))
    except Exception, e:
        print 'Create database first time so this error is ignore', e
        operations.append(
                migrations.AddField(
                model_name='products',
                name='stores',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stores'),
                preserve_default=False,
            ))

    
