# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20181023_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='soft_delete',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='soft delete'),
        ),
    ]
