# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20181024_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='address',
            field=models.CharField(default=123, max_length=250, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipinfomations',
            name='address',
            field=models.CharField(max_length=250, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.CharField(max_length=250, verbose_name='phone'),
        ),
    ]
