# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20181024_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
    ]
