# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20181027_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupuserpermissions',
            options={'verbose_name': 'GroupUserPermission', 'verbose_name_plural': 'GroupUserPermission'},
        ),
        migrations.AlterUniqueTogether(
            name='groupuserpermissions',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='groupuserpermissions',
            name='content_type',
        ),
    ]
