# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20181030_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupusers',
            name='name',
            field=models.CharField(choices=[('customer', 'customer'), ('store', 'store'), ('owner', 'owner')], default='customer_group', max_length=250, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='orderinfomations',
            name='status_order',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('accept', 'Accept'), ('shipping', 'Shipping'), ('done', 'Done')], default='create', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderinfomations',
            name='status_payment',
            field=models.CharField(choices=[('payment_error', 'Payment Error'), ('pending', 'Pending'), ('done', 'Done')], default='pendding', max_length=250, verbose_name='status_payment'),
        ),
    ]
