# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20181102_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfomations',
            name='status_order',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('shipping', 'Shipping'), ('completed', 'Completed')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderinfomations',
            name='status_payment',
            field=models.CharField(choices=[('payment_error', 'Payment Error'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=250, verbose_name='status_payment'),
        ),
    ]
