# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20181103_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfomations',
            name='money_usd',
            field=models.FloatField(blank=True, max_length=250, null=True, verbose_name='money usd'),
        ),
        migrations.AlterField(
            model_name='orderinfomations',
            name='money',
            field=models.IntegerField(blank=True, max_length=250, null=True, verbose_name='money'),
        ),
    ]
