# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20181112_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_usd',
            field=models.FloatField(blank=True, null=True, verbose_name='price usd'),
        ),
    ]
