# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20181118_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='location'),
        ),
    ]
