# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_stores_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='address'),
        ),
    ]
