# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20181208_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='cart_product_rel', through='app.CartDetail', to='app.Products'),
        ),
    ]
