# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20181212_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
